// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm57eIPOxez7FkOKPidKsoiwGm9RmblDU',
    appId: '1:875629801749:web:2d65b03436713ca0bdf91c',
    messagingSenderId: '875629801749',
    projectId: 'portable-health-kits-f1986',
    authDomain: 'portable-health-kits-f1986.firebaseapp.com',
    storageBucket: 'portable-health-kits-f1986.firebasestorage.app',
    measurementId: 'G-4ZC8PTQH12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-zV1Cka9giZUG7vRCwN9VBctGDpFiXX8',
    appId: '1:875629801749:android:3d7fb71a259e9663bdf91c',
    messagingSenderId: '875629801749',
    projectId: 'portable-health-kits-f1986',
    storageBucket: 'portable-health-kits-f1986.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCDutbrNd2Djs5YzWmHPHM9f1N4SsTVQQ',
    appId: '1:875629801749:ios:fb178a7a0a75f71abdf91c',
    messagingSenderId: '875629801749',
    projectId: 'portable-health-kits-f1986',
    storageBucket: 'portable-health-kits-f1986.firebasestorage.app',
    iosBundleId: 'com.example.portableHealthKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCDutbrNd2Djs5YzWmHPHM9f1N4SsTVQQ',
    appId: '1:875629801749:ios:fb178a7a0a75f71abdf91c',
    messagingSenderId: '875629801749',
    projectId: 'portable-health-kits-f1986',
    storageBucket: 'portable-health-kits-f1986.firebasestorage.app',
    iosBundleId: 'com.example.portableHealthKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm57eIPOxez7FkOKPidKsoiwGm9RmblDU',
    appId: '1:875629801749:web:5c41f9693a760f7cbdf91c',
    messagingSenderId: '875629801749',
    projectId: 'portable-health-kits-f1986',
    authDomain: 'portable-health-kits-f1986.firebaseapp.com',
    storageBucket: 'portable-health-kits-f1986.firebasestorage.app',
    measurementId: 'G-8DPBVW0B7C',
  );
}
