// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdXSX9jE3nxwY5Z7ppRRmmAnVfN-9mbXE',
    appId: '1:663729522895:web:10c71af88820f13fcf8fba',
    messagingSenderId: '663729522895',
    projectId: 'portable-health-kit-b1f2f',
    authDomain: 'portable-health-kit-b1f2f.firebaseapp.com',
    storageBucket: 'portable-health-kit-b1f2f.firebasestorage.app',
    measurementId: 'G-K516GPE69D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9-Fx1ABy71Fm8wVhsAmWeU9uCTq86Rho',
    appId: '1:663729522895:android:b4f1180b4deb99b6cf8fba',
    messagingSenderId: '663729522895',
    projectId: 'portable-health-kit-b1f2f',
    storageBucket: 'portable-health-kit-b1f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4EkDi45BKjnS-fn4-BJb1Or09Nc0GqFo',
    appId: '1:663729522895:ios:76bb53f7795958adcf8fba',
    messagingSenderId: '663729522895',
    projectId: 'portable-health-kit-b1f2f',
    storageBucket: 'portable-health-kit-b1f2f.firebasestorage.app',
    iosBundleId: 'com.example.portableHealthKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4EkDi45BKjnS-fn4-BJb1Or09Nc0GqFo',
    appId: '1:663729522895:ios:76bb53f7795958adcf8fba',
    messagingSenderId: '663729522895',
    projectId: 'portable-health-kit-b1f2f',
    storageBucket: 'portable-health-kit-b1f2f.firebasestorage.app',
    iosBundleId: 'com.example.portableHealthKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdXSX9jE3nxwY5Z7ppRRmmAnVfN-9mbXE',
    appId: '1:663729522895:web:7763a82b2d1ca87acf8fba',
    messagingSenderId: '663729522895',
    projectId: 'portable-health-kit-b1f2f',
    authDomain: 'portable-health-kit-b1f2f.firebaseapp.com',
    storageBucket: 'portable-health-kit-b1f2f.firebasestorage.app',
    measurementId: 'G-BHGJR0NHMQ',
  );

}